name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [macOS-latest, ubuntu-18.04, windows-latest]
    steps:
      - name: Setup ROS
        uses: seanyen/setup-ros@seanyen/devel
        with:
          required-ros-distributions: melodic
      - run: vcs --help
